### ISSUE TITLE
Call to undefined method writeString()

### ISSUE THREAD

**Issue by mprandot** [nfephp-org/sped-da#111]
Tentando imprimir uma NFCE no formato PDF.

`Call to undefined method Endroid\QrCode\QrCode::writeString()`

Procurando na classe (instalada junto com o projeto) QrCode, realmente não existe esse método, porém no repositório oficial existe:

https://github.com/endroid/qr-code/blob/master/src/QrCode.php

Estou errando em algo? Ou falta atualizar alguma versão no pacote?

**Comment by robmachado** [comment]
Não sei onde você está olhando mas a classe Danfce.php tem a chamada do endroid\qrcode na linha 21

use Endroid\QrCode\QrCode;

**Comment by mprandot** [comment]
Na linha 812 da classe Danfce.

$pic = 'data://text/plain;base64,' . base64_encode($qrcode->writeString());

o código está chamando o método writeString, que não existe na classe QrCode.

**Comment by mprandot** [comment]
Outra coisa que notei, no sped-da/sped-nfe não existe a dependência do pacote qr-code, apenas no posprint, isso não deveria ser "global"? Talvez adicionado como dependencia no repo common?

**Comment by augustoalvess** [comment]
Estou enfrentando exatamente o mesmo problema...

**Comment by JozeanneB** [comment]
Tive um problema similar.
Verifique se a versão do endroid/qrcode instalada é a 2.5.0 (ou >=2). 

Se não for essa versão pode estar faltando alguma dependência.
Instalei o ext-gd e não tive mais problemas com impressão de gd.

**Comment by robmachado** [comment]
Seguinte ! uma das alterações feita por um colega acabou quebrando o FPDF justamente  bloco responsável por lidar com a imagem do QR, já corrigi mas podem usar um release anterior ou esperar eu subir um novo release com a correção que está em MASTER
