### ISSUE TITLE
tag lota não existe no Ct-e 3.0

### ISSUE THREAD

**Issue by tiagooliveira1** [nfephp-org/sped-da#126]
Prezados,

ao tentar gerar um DACTE OS (DacteOSV3), é levantado erro na linha 1488
Undefined property: NFePHP\DA\CTe\DacteOSV3::$lota,
informando ausência da proprietade $this->lota.

Acredito que a tag lota só existe na versão 2.0 do layout, e retirada em versão posterior. Posso fazer a alteração e solicitar um pull request?

**Comment by gustavodebiasi** [comment]
A principio é isso mesmo @tiagooliveira1 . 
Pode retirar e fazer o pull request.
