### ISSUE TITLE
Alpha channel not supported

### ISSUE THREAD

**Issue by JulianoAmaralChaves** [nfephp-org/sped-da#127]
Ao tentar imprimir a DANFe usando uma logo com transparência da o erro "Alpha channel not supported"

**Comment by robmachado** [comment]
Não dá para usar ainda logo com transparencia

**Comment by JulianoAmaralChaves** [comment]
@robmachado criei um pull requeste incluindo suporte para PNG com transparência, acho que será útil

**Comment by robmachado** [comment]
Isso foi corrigido
