### ISSUE TITLE
QRcode não esta imprimindo corretamente

### ISSUE THREAD

**Issue by JulianoAmaralChaves** [nfephp-org/sped-da#129]
Usando o exemplo da DANFC-e, o QRCode não esta imprimindo corretamente, eu preciso configurar algo para que imprima corretamente?

Segue abaixo de como ficou o QRCode impresso

![image](https://user-images.githubusercontent.com/4882986/40136275-cbd712d0-591d-11e8-9c38-def66a73e4ef.png)

**Comment by robmachado** [comment]
Use a versão mais atual
