### ISSUE TITLE
Informacao de Rastro - Lote e Validade

### ISSUE THREAD

**Issue by angelomr** [nfephp-org/sped-da#141]
Arquivo:  sped-da/src/NFe/Danfe.php

No arquivo acima, na linha 2256, ha um erro no IF, pois o mesmo somente verifica se a variavel rastreio existe com o "isset", quando o correto seria verificar com o "empty", fazendo que as informacoes de rastro de produtos que tenham a tag "rastro" (mas nao tenham a tag "med") nao sejam exibidas.

O arquivo esta com este trecho de codigo:

```
        $rastro = $prod->getElementsByTagName("med");
        if (!isset($rastro)) {
            $rastro = $prod->getElementsByTagName("rastro");
        }

```
O correto seria:

```
        $rastro = $prod->getElementsByTagName("med");
        if (empty($rastro)) {
            $rastro = $prod->getElementsByTagName("rastro");
        }

```

**Comment by daniel2mind** [comment]
Boa tarde amigo... realizei a manutenção informada e em alguns casos específicos, essa alteração não se aplicou.

Da forma abaixo, me atendeu legal (alteração na linha 2255), pois atende tanto os usuários que AINDA estão na versão 3.10, quanto aos usuários que utilizam a NF-e 4.00:
`$rastro = $prod->getElementsByTagName("rastro");
        if (empty($rastro)) {
            $rastro = $prod->getElementsByTagName("med");
        }`

**Comment by angelomr** [comment]
Eu não testei na versão 3.10.

Testei desta forma que você colocou e também funciona.

Agora é só esperar o pessoal resolver atualizar a biblioteca com uma desses 2 jeitos.
