### ISSUE TITLE
Arquivo XML

### ISSUE THREAD

**Issue by limabibi** [nfephp-org/sped-da#154]
Olá bom dia,

A função 

$xml = $nfe->getXML();

Me retorna apenas o texto do XML, mas eu preciso salvar o arquivo XML. Como posso fazer isso com a NFE 4.0?

Desde já grata.

**Comment by robmachado** [comment]
file_put_contents

**Comment by limabibi** [comment]
Obg, e por favor não me acha noob, eu sou apenas uma desenvolvedora junior me aventurando.
