### ISSUE TITLE
Erro ao gerar o DACTE: Undefined variable: qCarga

### ISSUE THREAD

**Issue by ghost** [nfephp-org/sped-da#156]
Estou utilizando este projeto no meu trabalho, mas apresentou algumas inconsistências para alguns CTes. Ao pedir para gerar o PDF, apresenta a seguinte mensagem: **Erro ao gerar o DACTE: Undefined variable: qCarga**. 

Debugando o código do arquivo **DacteV3.php**, eu vi que esse erro acontece quando vai capturar os valores de peso e quantidade da carga transportada. Segue o trecho no qual apresentam os erros:

![image](https://user-images.githubusercontent.com/42357887/44111034-ba7236fe-9fd7-11e8-9ebd-b224c8637797.png)

A tag **infQ** está condicionado no **if** até achar o valor correspondente ao quilo (01). Só que os CTes nem sempre terão apenas 3 destas tags. Os CTes nos quais estou tendo problemas apresentam 5 tags **infQ**.

Ao meu olhar, o correto seria colocar esse trecho de código dentro de um loop, percorrendo todas as tags **infQ**, pois nunca sabemos a quantidade destas tags para cada CTe.

Eu posso estar colaborando e consertando este erro, ou alguém responsável irá rever este trecho?

**Comment by xandyalexandrec** [comment]
@andreparpaiola sei que ja faz quase um ano desta issue, mas estou passando por uma situação parecida, como você solucionou este problema?

**Comment by andreparpaiola** [comment]
Olá, na época como houve demora na minha resposta e eu estava com uma certa urgência, resolvi por conta própria no meu arquivo local do projeto, seguindo o **loop** que eu havia sugerido. 

Para mim, funcionou perfeitamente.

Espero ter ajudado.

**Comment by jefersonalmeida** [comment]
Saudações,
Se possivel alterar a linha **1750** do arquivo **NFePHP\DA\CTe\DacteV3** para: 

```
        $qCarga = 0;
        for ($i = 0; $i <= $this->infQ->count(); $i++) {
            if ($this->getTagValue($this->infQ->item($i), "cUnid") == '01') {
                $qCarga = $this->getTagValue($this->infQ->item($i), "qCarga");
            }
        }
```

**Comment by tavinus** [comment]
> 
> 
> Saudações,
> Se possivel alterar a linha **1750** do arquivo **NFePHP\DA\CTe\DacteV3** para:
> 
> ```
>         $qCarga = 0;
>         for ($i = 0; $i <= $this->infQ->count(); $i++) {
>             if ($this->getTagValue($this->infQ->item($i), "cUnid") == '01') {
>                 $qCarga = $this->getTagValue($this->infQ->item($i), "qCarga");
>             }
>         }
> ```

Linha 1750 é pra versão antiga.  
Na versão atual esse trecho fica na linha 1721.  
https://github.com/nfephp-org/sped-da/blob/master/src/CTe/DacteV3.php#L1721  
  
Cheers!  
Gus
