### ISSUE TITLE
Logo via URL

### ISSUE THREAD

**Issue by thmrdev** [nfephp-org/sped-da#158]
Boa tarde Pessoal,

Utilizo a API em alguns projetos, onde estes consomem um único projeto centralizado da API.
E me surgiu a necessidade de dar um GET na logo que pode ou não estar em outro server.

Neste caso em específico está em um servidor diferente.
Gostaria de estudar em conjunto com vocês a possibilidade de através de uma URL carregar a logo.

Desde já, agradeço a atenção.

Obrigado.

**Comment by robmachado** [comment]
Você pode fazer o seguinte:

**Mas lembre-se que deve usar nesse caso apenas imagens JPG**

```php
error_reporting(E_ALL);
ini_set('display_errors', 'On');
require_once '../bootstrap.php';

use NFePHP\DA\NFe\Danfe;

$url = "https://upload.wikimedia.org/wikipedia/pt/9/9a/Grupomateus_logo.jpg";

try {
    $pic = 'data://text/plain;base64,'.base64_encode(file_get_contents($url));
    $danfe = new Danfe($xml, 'P', 'A4', $pic, 'I', '');
    $id = $danfe->monta();
    $pdf = $danfe->render();
    
    header('Content-Type: application/pdf');
    echo $pdf;
} catch (\Exception $e) {
    echo "Ocorreu um erro durante o processamento :" . $e->getMessage();
}    
```

**Comment by thmrdev** [comment]
Opa, deu certo \o/.
Para "png", conhece alguma solução semelhante?

Obrigado mais uma vez.

**Comment by robmachado** [comment]
Calma colega !! dou a mão e você quer o braço também !

**Comment by robmachado** [comment]
Dependendo do formato do PNG irá funcionar também da mesma forma

**Comment by thmrdev** [comment]
Pesquisando, por aqui.
No formato PNG não funcionou, se encontrar algo posto por aqui.

Obrigado.

**Comment by robmachado** [comment]
Como eu disse irá depender do formato do PNG

**Comment by robmachado** [comment]
O que você pode fazer é no SEU script, trazer a IMAGEM, usar o GD para converte-la para JPG e passar como RAW para a classe. Tudo em memória sem usar o disco.

**Comment by thmrdev** [comment]
Sim, compreendido!
Como eu disse se encontrar algo diferente posto por aqui.

Obrigado.

**Comment by thmrdev** [comment]
Roberto,

Obrigado pelo help.
Encontrei um exemplo e utilizei como base.

Segue, caso alguém também tenha este tipo de problema:

`
 $image = imagecreatefrompng($retorno->detalhes[0]->IMAGEM);
 $bg = imagecreatetruecolor(imagesx($image), imagesy($image));
 imagefill($bg, 0, 0, imagecolorallocate($bg, 255, 255, 255));
 imagealphablending($bg, true);
 imagecopy($bg, $image, 0, 0, 0, 0, imagesx($image), imagesy($image));
 imagedestroy($image);
 $quality = 50; // 0 = worst / smaller file, 100 = better / bigger file
 imagejpeg($bg, "nfe/{$this->configOBJ->cnpj}/{$this->configOBJ->cnpj}".".jpg", $quality);
 imagedestroy($bg);
`

**Comment by robmachado** [comment]
Pode usar para PNG a solução que lhe passei deverá funcional para a maioria dos PNGs

**Comment by codeatt** [comment]
Pessoal, Formatos suportados:

jpg, png - tamanho máximo: 100X100 pixels. peso máximo: 10MB
