### ISSUE TITLE
Melhoria: Permitir múltiplos layouts DANFE

### ISSUE THREAD

**Issue by NettoPassaro** [nfephp-org/sped-da#159]
@robmachado 

Estava pensando em contribuir com uma nova funcionalidade, que permita que o desenvolver crie layouts personalizados do DANFE, usando HTML e tags com o nome dos campos.

Acham interessante/viável?

Obrigado

**Comment by robmachado** [comment]
No passado tentamos usar esse recurso porém a conversão do HTML é lenta e muito falha. Em outros casos tentaram usar recursos em java e c, mas isso implica em instalar "coisas estranhas" no servidor o que nem sempre é viável.
Acredito pessoalmente em usar apenas e exclusivamente PHP ! e minha recomendação é o uso do TCPDF em sua nova versão. 
Outra coisa que você deve lembrar é que a grande maioria dos usuários são do tipo "Ctrl-C Ctrl-V" ou seja querem usar  algo pronto e simples e nem olha o código ou qualquer documentação que seja fornecida.
Mas existe espaço para outras ideias :+1:

**Comment by NettoPassaro** [comment]
Roberto,

Entendido! Obrigado!
