### ISSUE TITLE
Imprimir várias notas ao mesmo tempo

### ISSUE THREAD

**Issue by Jack184** [nfephp-org/sped-da#176]
Bom dia amigo.

Primeiramente gostaria de agradecer pela maravilha biblioteca. Graças a ela consegui implementar um sistema gerador notas. Só estou com um probleminha... Não estou conseguindo imprimir várias notas ao mesmo tempo... Isso é possível? Você teria um exemplo de como fazer isso?

**Comment by olavocneto** [comment]
Olá @Jack184 ,
Se é possível? Exclusivamente pela biblioteca eu acredito que não. Mas, sim, possível na maneira como usa a biblioteca. Se baseando que está mencionando o DANFE acredito que uma rotina provável é iterar as suas NF-e e então ir criando o DANFE da mesma maneira como se fosse uma única NF-e. O final é um arquivo compactado com tudo? 1 PDF só com todos os DANFE concatenados? Também acredito que é com você manipulando o retorno do `render `. Posso estar engado também e algo já está pronto na biblioteca :smile: 

Pode ser que o fórum do projeto te ajude: Por exemplo: https://groups.google.com/forum/?hl=pt-br#!searchin/nfephp/pdf$20danfe$20m%C3%BAltiplos%7Csort:date

Abraço,

**Comment by Jack184** [comment]
> 1 PDF só com todos os DANFE concatenados?

Essa é a ideia @olavocneto . Como na minha solução as nota são geradas em massa,  seria conveniente gerar somente um PDF com várias páginas(uma nota por página). Assim eu poderia imprimir tudo de uma vez. Acredito que somente adaptando ou criando uma nova classe que estende a classe Danfe com um método pra adicionar mais páginas(Danfe->addXml()), pois hoje o xml é passado no construtor. Obrigado pelas dicas. Se eu conseguir implementar isso eu posto aqui.

**Comment by Jack184** [comment]
Consegui agrupar as NFes @olavocneto. Obrigado pela ajuda! Utilizei a biblioteca FPDI https://github.com/Setasign/FPDI
Segue o código para quem precisar:

    // Intancia FPDI
    $pdf = new Fpdi();
    
    // Cria pasta temporária para armazenar as notas que serão agrupadas
    $folder = 'tmp';
    if (!file_exists($folder)) {
        mkdir($folder, 0700, true);
    }
    
    // Loop para adicionar as notas a seleção de impressão
    for($i = 0; $i < count($notas); $i++) {
        
        // Busca o xml da nota na base de dados
        $query = 'SELECT xml_autorizado FROM nota WHERE id_n = :id_n';
        $stmt = $dbh->prepare($query);
        $stmt->execute([':id_n' => $notas[$i]]);
        $nota = $stmt->fetch(PDO::FETCH_ASSOC);
        
        $danfe = new Danfe($nota['xml_autorizado'], 'P', 'A4', '../../img/global/logo-nfe.jpeg', 'D', '');
        $id = $danfe->montaDANFE();
        $nfe_pdf = $danfe->render();
        
        // Salva a nota na pasta temporária
        file_put_contents($folder.'/'.'nfe'.$i.'.pdf', $nfe_pdf);
        
        // Adiciona uma página a instância
        $pdf->AddPage();
        $pdf->setSourceFile($folder.'/'.'nfe'.$i.'.pdf');
        $tplId = $pdf->importPage(1);
        $pdf->useTemplate($tplId, 0, 0, 210);
    }
    
    // Mostra o pdf no navegador
    $pdf->Output();
    
    // Apaga os arquivos temporários após renderizar as notas agrupadas por páginas
    for($i = 0; $i < count($notas); $i++) {
        unlink($folder.'/'.'nfe'.$i.'.pdf');
    }`

**Comment by olavocneto** [comment]
Boa, isso aí! A biblioteca fica com a responsabilidade de lidar as normas e padrões do exigidas pelo estado e outros órgãos públicos e nós em nossos sistemas nos adequamos as necessidades dos usuários. Feche a issue, por favor.

Abraço,

**Comment by Jack184** [comment]
Fechando aqui @olavocneto. Obrigado por tudo!
