### ISSUE TITLE
Danfe.php ainda procura a tag <indPag> na tag <ide> porém agora ela fica na <pag>

### ISSUE THREAD

**Issue by alexrosabr** [nfephp-org/sped-da#177]
https://github.com/nfephp-org/sped-da/blob/29f1f035523e8941d55ed4151768b41f40810e44/src/NFe/Danfe.php#L1660

Deveria procurar no vetor detPag da tag pag.

**Comment by alexrosabr** [comment]
Conforme NT 2016.002 o campo "indPag" foi removido da "ide"
![image](https://user-images.githubusercontent.com/18428330/84394656-9d13ef80-abd3-11ea-82f6-abd61ea1c5c4.png)

E acrescentado na "pag"
![image](https://user-images.githubusercontent.com/18428330/84394732-b87efa80-abd3-11ea-9060-a417f49f0581.png)

**Comment by robmachado** [comment]
Ao que eu saiba TAMBÉM procura na tag "nova" da versão 4.00 e coloca na DANFE, isso foi mantido pois muitas notas do passado AINDA podem ser impressas na DANFE para fins variados. 
Os usuários comuns não sabem LER o XML e gostam de imprimir esses documentos

**Comment by robmachado** [comment]
Vou investigar suas alegações !
