### ISSUE TITLE
NFCe em contingência offline

### ISSUE THREAD

**Issue by ocult** [nfephp-org/sped-da#181]
Boa noite,

Preciso imprimir uma NFCe emitida em contingência off-line "<tpEmis>9</tpEmis>".

Já consigo fazer essa impressão?

Se não... vou criar uma fork para essa demanda, pode ser?

**Comment by robmachado** [comment]
Claro mas veja os PR que já estão pendentes, muitos por falhas na estrutura de código.
Use o PSR2 e rode o composer phpcbf e composer phpcs antes de submeter.

**Comment by ocult** [comment]
Pronto no PR #184
