### ISSUE TITLE
Caracteres com codificação HTML na impressão do DANFE

### ISSUE THREAD

**Issue by Eihen** [nfephp-org/sped-da#186]
Bom dia.

Durante a geração do XML no `sped-nfe` alguns campos, como `$emit->xNome` e `$dest->xNome`,  são limpados com a função `Strings::replaceUnacceptableCharacters()` do `sped-common`, a qual traduz alguns caracteres especiais para o seu código HTML.
Porém, ao gerar o DANFE esses caracteres nunca são retornados para sua forma original, resultando na exibição de seus códigos HTML na impressão.

Estou disposto a abrir um PR para corrigir o problema, porém gostaria de discutir a solução mais adequada.
Afim de preservar os escopos atuais, acredito que uma função para reverter esses caracteres deva ser adicionada a classe `Strings` do `sped-common` e aplicada a esses campos antes da geração de seus respectivos `textboxes`, ou até mesmo na própria função `pTextBox` para diminuir a chance de erros.

Edit: Acabo de perceber que `sped-da` não depende de `sped-common`, então acho que a solução que apresentei acima não é adequada.

**Comment by luishgp** [comment]
Estamos passando pelo mesmo problema com o _ampersand_ (&), detectei um problema na geração do XML onde no emitente era feito o replace duas vezes do & por \&amp; resultando em \&amp;amp;. 

Porem isto não resolveu o problema com a impressão. 

Agora o XML está sendo gerado corretamente, sendo necessário apenas um decode para a impressão.

Até conseguirmos ajustar a impressão no componente, estou utilizando o método _htmlspecialchars_decode_ antes de passar o XML para o sped-da

**Comment by robmachado** [comment]
O caminho para resolver a impressão acho que é esse mesmo 

Roberto
