### ISSUE TITLE
Bug ao montar o PDF com múltiplas chaves referenciadas

### ISSUE THREAD

**Issue by inegrao** [nfephp-org/sped-da#190]
Ao fazer uma nota com natureza de operação EXPORTAÇÃO preciso referenciar dezenas de notas fiscais em exportação indireta. O PDF criado junta todas essas referencias adicionais na primeira página deixando as próximas páginas livres e fazendo uma confusão visual enorme.

Em anexo o PDF para melhor entendimento do BUG.
[4.pdf](https://github.com/nfephp-org/sped-da/files/2870076/4.pdf)

**Comment by robmachado** [comment]
Faça um favor envie esse XML em anexo por email para linux.rlm@gmail.com que vou aproveitar e fazer umas alterações no DANFE.
