### ISSUE TITLE
Migrar FPDF 1.6 para versão 1.8

### ISSUE THREAD

**Issue by andersonls** [nfephp-org/sped-da#199]
Estou criando esta issue referente ao PR #198, para discutir a estratégia de migração.

No PR o @tonicospinelli sugeriu 
> que a classe `Pdf` seja composta pelo FPDF recebendo no construtor e implementando uma interface.

Porém, se criarmos uma interface o FPDF vai precisar implementar e teremos que alterar o código do FPDF, além de ser necessário refatorar a classe `Pdf` inteira.

Eu aindei olhando o changelog do FPDF e não teve nenhuma modificação que pudesse quebrar a compatibilidade dos pdf gerados. Eu rodei todos os exemplos que tem em `examples` comparando o pdf gerado antes e após a migração e todos resultaram em pdf idênticos.
Se quiserem ter mais certeza, eu posso criar mais exemplos, só preciso de XMLs de novos casos de uso.

O que vocês acham?

**Comment by tonicospinelli** [comment]
boaa!! abrir essa discussão aqui é uma ótima ideia.

acho que não me expressei muito bem quando fiz este comentário, tentarei ser mais claro.

A classe Pdf poderia receber uma interface para definir um "driver" de criação de Pdf, assim como o PDO tem para mysql, sqlite e  afins...

Usando composição nós ganhamos por não depender exclusivamente da library `FPDF` e sabendo que o PDF de Danfe deve estar em um formato definido, tudo isso poderia ser padronizado. Eu entendo que pode dar um baita trabalho toda essa refatoração e o ganho pode ser bem baixo inicialmente.

Eu só fico preocupado com a manutenção disso ou mesmo com a remoção de alguma biblioteca de dentro do packagist

**Comment by andersonls** [comment]
@tonicospinelli Pensando um pouco mais nesse teu comentário, eu acho que a classe `Pdf` já seria o _driver_ propriamente dito.

Estou pensando no seguinte:

```php
interface DriverInterface {
    public function render();
    public function setMargins();
    public function setDrawColor();
    ....
}

class Pdf implements DriverInterface {
    //Classe que utiliza o FPDF 1.8 do composer, continua sendo a mesma versão do meu PR
}

class PdfLegacy implements DriverInterface {
    //Classe que utiliza o FPDF 1.6 como está atualmente, continua idêntica a que tem hoje.
}

class Common {
    protected $driver; //Substitui o $pdf
    public function __construct(DriverInterface $driver) {
        $this->driver = $driver;
    }
}
```

Olhando no código já existia uma semente implantada para transformar o `Pdf` num driver, o método `montaDANFE`, por exemplo, aceita como parâmetro um nome de classe para utilizar ao invés da `Pdf`, porém sem nenhum tipo de validação.

**Comment by robmachado** [comment]
@andersonls eu iria um passo diferente
A ideia original do sped-da era que:
- A partir de uma unica classe pudesse gerar QQ documento SPED (NFe, NFCe, CTe, MDFe, CCe, Canc, etc.) em PDF
- Que essa conversão fosse padronizada com INTERFACES
- Usando uma classe regularmente mantida para gerar os PDFs 
- Podendo usar "Containers" para a injeção de dependências e outras classes de geração de PDF disponíveis

Mas isso é bem complicado de fazer e manter ! Para quem como nós (não usa tudo) ou não tem tanto tempo disponível.

**Comment by tonicospinelli** [comment]
@robmachado na verdade, estamos levantando um ponto que é a abstração para usar uma engine eterna que gera PDF, mas que não gere impacto no código do SPED-DA*. Posteriormente, poderemos introduzir novas engines para converter para HTML se achar que é viável.

@andersonls é essa a linha de raciocínio mesmo, apenas mudaria um pouco os nomes para ser mais semântico. Cada driver recebe no construtor sua versão do FPDF ou outro driver que queiramos disponibilizar junto com o Sped-DA*

```php
interface Pdf\Driver {}

class Pdf\Driver\FPDF18 implements Pdf\Driver {
    public function __constructor(FPDF $engine) {}
}

class Pdf\Driver\FPDF16 implements Pdf\Driver {
    public function __constructor(Legacy\FPDF\Fpdf $engine) {}
}

class Pdf implements Pdf\Driver {
    private $driver
    public function __constructor(Pdf\Driver $driver) {
        $this->driver = $driver
    }
}
```

**Comment by robmachado** [comment]
Muito bem ... estou levantando outra BRANCH a v1.0 para seguirmos nessa linha 
Assim que essa branch estiver funcional passamos para master e a atual passa para uma branch histórica como v0.1
E já que faremos isso vou iniciar a refatoração de algumas classes.
Quanto a FPDF 1.8 vou insistir em NÃO USAR essas do GITHUB pois estão com o codigo ruim, vou trazer a FPDF 1.8 para uma pasta LIBS e refatorar
