### ISSUE TITLE
Grupo F e G para Local de Retirada e Entrega

### ISSUE THREAD

**Issue by rabraga** [nfephp-org/sped-da#204]
Bom dia!

Conforme NT 2018.005 Versão 1.20 – Março de 2019 pode ser impresso no DANFE em quadros separados os endereços de entrega e retirada. Isto não é obrigatório. Vale a pena fazermos?

Uma transportadora disse que só aceitará transporte se esta informação vier registrada no quadro específico conforme sugestão da SEFAZ.

Atualmente essa informação está indo nas INFORMAÇÕES COMPLEMENTARES.

**Comment by guicouto** [comment]
Apenas para ajudar na documentação, abaixo está a orientação da NT 2018.005 referente a sugestão de como poderão ser exibidos os campos no DANFE:

![orientacao_nf_2018_005_danfe](https://user-images.githubusercontent.com/8810377/57541666-f0a77000-7325-11e9-9670-b53db8069b06.png)

**Comment by robmachado** [comment]
Quem estiver a fim a colaborar, pode introduzir essa alteração na classe.

**Comment by guicouto** [comment]
Boa tarde @robmachado tentarei acrescentar essa modificação aqui. PR apenas na branch develop, certo?

**Comment by robmachado** [comment]
Pode usar o master mesmo desde que faça os devidos testes com várias NFe (com um numero crescente de itens até gerar umas 3 páginas)

**Comment by rabraga** [comment]
@guicouto ,
Boa tarde, tudo bem?
Como está esta implementação? Posso ajudar? Já fez algo?

**Comment by alexrosabr** [comment]
Senhores, o código do PR #206 não serve? Atualmente o endereço de entrega está saindo nas [observações](https://github.com/nfephp-org/sped-da/blob/master/src/NFe/Danfe.php#L472), o código que o @emersondiegofeltrin postou parece estar imprimindo no quadro específico, conforme a NT 2018.005.

**Comment by emersondiegofeltrin** [comment]
Boa tarde.
@alexrosabr exato! Essa alteração foi implementada e está no PR #206 que foi fechado sem merge.

**Comment by robmachado** [comment]
Não serão inclusas nenhuma PR que não atender ao PSR-2 !
Todas as PRs deve passar no processo de validação automática para serem inclusas.
E deve ser descrito o MOTIVO da PR sendo remetida.

**Comment by hugowalbertoalves** [comment]
Emerson,
passei seu código por um validador PSR-2 online e deu apenas 2 erros a serem corrigidos, deve usar "\n" e não "\r\n" e precisa deixar uma linha em branco no final do código, just it! Pode verificar e subir seu código?

**Comment by emersondiegofeltrin** [comment]
@hugowalbertoalves altero sim, você pode reabrir o #206? Ou preciso realizar outro pull request?

**Comment by robmachado** [comment]
Preferencialmente faça outro PR

**Comment by emersondiegofeltrin** [comment]
Criado PR #289

**Comment by rabraga** [comment]
ok!
