### ISSUE TITLE
Impressão SAT

### ISSUE THREAD

**Issue by DaniloTurini** [nfephp-org/sped-da#205]
Estou querendo saber se alguém tem alguma classe de gerar um PDF de um xml SAT, pois estou precisando gerar PDFs dos xmls.

**Comment by NettoPassaro** [comment]
Olá @DaniloTurini 
Estou com a mesma necessidade aqui.

Eu tentei fazer usando o mesmo exemplo do CF-e ([aqui](https://github.com/nfephp-org/sped-da/blob/master/examples/testaDanfce.php)), mas não rolou...

Você conseguiu algo?

**Comment by DaniloTurini** [comment]
Não consegui.

Em ter, 30 de jul de 2019 às 12:21, Netto Passaro <notifications@github.com>
escreveu:

**Comment by NettoPassaro** [comment]
@DaniloTurini Achei um outro pacote que faz isso: [amosassis/cfe-printer](https://packagist.org/packages/amosassis/cfe-printer)
