### ISSUE TITLE
Impressão DANFE cancelada

### ISSUE THREAD

**Issue by dragonmaro** [nfephp-org/sped-da#208]
Queria saber se tem como fazer sair no código de barras da impressão da DANFE escrito CANCELADO para eu poder imprimir os xmls ja cancelados desta maneira.

**Comment by robmachado** [comment]
Para que seja impresso a mascara CANCELADA é necessário protocolar o cancelamento da NFe no XML autorizado usando o método cancelRegister() da classe Complements do sped-nfe
vide https://github.com/nfephp-org/sped-nfe/blob/master/docs/Complements.md
