### ISSUE TITLE
Novo DAMDFe 3.00a - Layout

### ISSUE THREAD

**Issue by Ramonrune** [nfephp-org/sped-da#210]
Na versão do MDF-e 3.00a foi alterado o DAMDFE. Agora deve constar um QR Code. O modelo pode ser encontrado em: https://dfe-portal.svrs.rs.gov.br/Mdfe/Documentos no documento MOC MDF-e 3.00a - DAMDFE.

A SEFAZ RS consta a implementação obrigatória até a data de 07 de Outubro de 2019, quando entrará em vigor a obrigatoriedade de exibição do QRCode no layout do DAMDFE.

**Comment by lukinhaspm** [comment]
Boa tarde, a data que vi é Jul/2019 em produção, aonde vc viu outubro?

O pacote do MDFe esta bem desatualizado, eu mesmo nao uso o sped-da para emitir a DAMDFe

**Comment by robmachado** [comment]
Pois é ninguém está dando as manutenções nesses pacotes relativos ao MDFe

**Comment by lukinhaspm** [comment]
> Boa tarde, a data que vi é Jul/2019 em produção, aonde vc viu outubro?
> 
> O pacote do MDFe esta bem desatualizado, eu mesmo nao uso o sped-da para emitir a DAMDFe

Apenas comentando,... eu vi que a DAMDFe é para outubro, mas existem mudanças no MDFe que uma delas é justamente o qrcode no XML... @Ramonrune isso você chegou a ajustar?

Abs

**Comment by Ramonrune** [comment]
Não, estou quase sem tempo ultimamente, então vim checar se já havia algo feito

**Comment by maisonsakamoto** [comment]
Pelo que li no MOC-VIsaoGeral entra em homologação em JUNHO e entra em Produção em JULHO. Isso não quer dizer que virou obrigatoriedade quer dizer que o web service vai receber tanto a versão 3.00 quanto a nova versão 3.00a.

No outro MOC-MDFe_AnexoII esta escrito tanto homologação quanto Produção a implantação para Outubro/2019 então pelo que entendi é que Outubro é a data limite para estar tudo funcionando em 3.00a seria isso mesmo ou me enganei ?

**Comment by Ramonrune** [comment]
Na noticia na integra, consta que que a versão 3.00a entra em produção em 15/07/2019, enquanto a obrigatoriedade da exibição do QR Code no DAMDFE entra em vigor em 07 de Outubro de 2019. Então, em julho serão publicados os webservices com as novas alterações. A partir de outubro se torna obrigatória a exibição do QR Code. 

Noticia na integra:

> Comunicado sobre as datas de implantação da versão 3.00a

> Comunicamos que foi publicado a versão 3.00a do Manual de Orientação do Contribuinte do MDF-e e seus anexos.

> Reforçamos que esta nova versão prevista para entrar em homologação a partir do dia 14 de junho de 2019 e em produção a partir do dia 15 de julho de 2019, contempla a atualização do schema do MDF-e dentre outras modificações.

> Relativamente à definição dos padrões do QRCode previstos no arquivo XML do MDF-e, cuja especificação das configurações para impressão no DAMDFE estão detalhadas no Anexo II – Manual de Especificações Técnicas do DAMDFE, serão implementadas a partir de 07 de Outubro de 2019, quando entrará em vigor a obrigatoriedade de exibição do QRCode no layout do DAMDFE.

> Da mesma forma, as RV G096 a G101 passarão a ser aplicadas em 01/07/2019 no ambiente de homologação e somente em 07 de Outubro de 2019 no ambiente de produção.

**Comment by lukinhaspm** [comment]
@Ramonrune obrigado, temos alguns dias então para ajustar o XML e já iniciar os ajustes da impressão. abs

**Comment by joaoroyosilva** [comment]
Boa noite pessoal, eu fiz as alterações, porém eu tenho um problema com o Travis rsrsrs. Meu pull request está preso. Ficou faltando somente o evento da inclusão de DFe

**Comment by lukinhaspm** [comment]
grande @joaoroyosilva !
valeu mesmo
uma dúvida, e no MDFe? Você mudou também as classes para os novos campos?
abs

**Comment by joaoroyosilva** [comment]
Eu só fiz a inclusão dos métodos para gerar as tags no XML. Nos mesmos moldes dos outros. Eu ainda não fiz a integração com as novas classes da V5. A chamada ficou:

`
$maker->taginfRespTec($CNPJ,$xContato,$email,$fone);
$maker->taginfMDFeSupl();
$maker->tagQRCode();
`

Agora precisa fazer as alterações para conseguir completar o pull request. Eu deixei alterado o composer para eu conseguir subir no packgist pra usar.

**Comment by lukinhaspm** [comment]
beleza muito obrigado
Eu vi no seu repositorio o pull request lá tb
vou adaptar aqui
valeu mesmo

**Comment by lukinhaspm** [comment]
Bom dia pessoal,
Teve um schema que foi ajustado do MDFe, é importante atualizar.
Ps. a versão 3.00 ainda está funcionando em prod.
Abs
