### ISSUE TITLE
Orientação retrato - DANFE

### ISSUE THREAD

**Issue by Matheuscruztj** [nfephp-org/sped-da#220]
Bom dia,
Estou precisando ajustar o layout da DANFE para orientação de retrato, porém escolhendo ou fixando o modo, o documento sai da mesma maneira (paisagem). Alguém sabe informar se possui alguma outra configuração a ser feita ou outro pacote que gere o documento em retrato?

**Comment by robmachado** [comment]
A escolha "Landscape" ou "Portrait" está estabelecido pelo "tpImp" no XML do documento
