### ISSUE TITLE
Contribuição com o projeto

### ISSUE THREAD

**Issue by evertongx** [nfephp-org/sped-da#23]
Oi @robmachado ,

estou começando a trabalhar com CTe na empresa que trabalho e estou interessado em estar colaborando com o projeto, pois nossa api é em php. Percebi que vcs passaram todos os DAs para aqui só que fui verificar as diferenças do DACTE na versão antiga (https://github.com/nfephp-org/nfephp/blob/8f0bf1d158854abff1a68560707f34f9fce4a096/libs/CTe/DacteNFePHP.class.php) e está bem diferente da que está aqui. Tem alguém trabalhando nela? Caso não tenha, quais seriam as implicações para que pudesse ajudar no desenvolvimento?

**Comment by robmachado** [comment]
@evertongx 

As classes ainda necessitam ser refatoradas para melhorar a usabilidade e a mantenabilidade.

Por ora não estou mexendo nessas classes do sped-da, pois estou com outras prioridades, mas também estou aguardando que o TCPDF seja liberado em sua nova versão, que por sinal está ficando muito boa.

Mas fique a vontade pra colaborar com o que quiser.

**Comment by evertongx** [comment]
@robmachado beleza, o pessoal aqui tem um fork do sped-da (https://github.com/financial/sped-da) então vou mandar uns pull-requests através dele. 

Só estou com uma duvida em relação o atributo `$situacao_externa`, verifiquei que na versão antiga que existe umas constantes com os possíveis valores, e aqui ele foi até retirado dos parâmetros do `montaDacte()` (https://github.com/nfephp-org/sped-da/blob/master/src/CTe/Dacte.php#L277), teria algum motivo pra isso ou posso trazer essa lógica de volta para classe?

**Comment by robmachado** [comment]
Essas variáveis não fazem sentido, na verdade !!

Pelos seguintes motivos:

1 - O parser par o PDF deve depender apenas do conteúdo do XML
2 - Quando existe um cancelamento é ideal adicionar o protocolo de
cancelamento ao XML
3 - Somente são impressas CTe Válidas ou ainda sem o protocolo para efeito
ilustrativos SEM VALOR FISCAL
4 - Não é razoável introduzir PARTICULARIEDADES numa classe como essa

E por ai vai


Roberto

**Comment by evertongx** [comment]
@robmachado  Então no caso da impressão do número do DPEC, verificar se o tipo de emissão é 4 já seria suficiente?
