### ISSUE TITLE
Problema no cabeçalho do DAMDFe

### ISSUE THREAD

**Issue by rafaelcouto** [nfephp-org/sped-da#239]
Bom dia,

No cabeçalho do DAMDFe está sendo exibido o CPF do motorista ao invés do CNPJ/CPF do emitente.

No construtor está assim:
**$this->emit = $this->dom->getElementsByTagName("emit")->item(0);
if ($this->dom->getElementsByTagName("CPF")->item(0)) {
            $this->CPF = $this->dom->getElementsByTagName("CPF")->item(0)->nodeValue;
        } else {
            $this->CNPJ = $this->dom->getElementsByTagName("CNPJ")->item(0)->nodeValue;
        }**

Sugestão de alteração:
**$this->emit = $this->dom->getElementsByTagName("emit")->item(0);
if ($this->emit->getElementsByTagName("CPF")->item(0)) {
            $this->CPF = $this->emit->getElementsByTagName("CPF")->item(0)->nodeValue;
        } else {
            $this->CNPJ = $this->emit->getElementsByTagName("CNPJ")->item(0)->nodeValue;
        }**

E uma dúvida, é correto formatar a I.E. no cabeçalho? Pois cada estado tem um padrão diferente.

Att.

**Comment by cleitonperin** [comment]
sobre a IE acho melhor nao formata-la;
sobre a correção cria um pull request pra ser mesclado por favor
