### ISSUE TITLE
Correção de Método

### ISSUE THREAD

**Issue by arielcannal** [nfephp-org/sped-da#25]
Olá!

Arquivo Legacy/Pdf, linha 826:

de:
`$this->detLineWidth($w);`

para:
`$this->setLineWidth($w);`

**Comment by robmachado** [comment]
@arielcannal fça um pull request que eu autorizo, no momento estou fora e não consigo alterar

**Comment by maisonsakamoto** [comment]
Pode fechar esse issue já entrou a correção, obrigado @arielcannal por avisar e corrigir!
https://github.com/nfephp-org/sped-da/commit/4c6904bd5263d064b8966abbd16c2d71e69872ed#diff-0fd26cb490d5816997aa497588d9da47
