### ISSUE TITLE
Pré-Visualizar

### ISSUE THREAD

**Issue by maisonsakamoto** [nfephp-org/sped-da#28]
Olá! No sistema gratuito de emissão do estado de SP, tem uma opção de pré-visualizar o CTe, seria possível alguém desenvolver essa parte ? ( ou me ajudar a fazer )
Obrigado desde já pela atenção!
Segue abaixo um exemplo:
![pre-visualizar](https://cloud.githubusercontent.com/assets/6425225/19644795/82d3fe30-99d0-11e6-83e1-cc92f776a405.PNG)

**Comment by robmachado** [comment]
haaaaãã !!

É só imprimir a DACTE com o CTe mesmo sem o protocolo

Roberto

**Comment by maisonsakamoto** [comment]
Oi Roberto, eu fiz umas modificações na Classe Dacte para imprimir com essa mensagem em marca d'agua e já me resolveu, não sei se é de interesse adicionar isso ao projeto, talvez isso seja particularidade então vou fechar, obrigado por responder

**Comment by robmachado** [comment]
Mailson ... pode submeter que podemos usar sim ... caso não esteja protocolado normalmente colocamos uma mensagem em marca dagua dizendo que é 'sem valor fiscal" ou algo do tipo
