### ISSUE TITLE
Dacte

### ISSUE THREAD

**Issue by cacio** [nfephp-org/sped-da#30]
Bom dia ,
tenho uma impressão de dacte do cte, mas o problema que acontece é que na parte dos DOCUMENTOS ORIGINÁRIOS eu tenho 17 notas e quando eu vo gera as chaves passam por cima de OBSERVAÇÃO E DADOS ESPECÍFICOS ABAIXO faz com que meu dacte mal visualizado , sera que alguém tem uma atualização disso para me auxiliar.
segue o link da imagem abaixo.
http://prodapro.com/cacio/Capturar.PNG

**Comment by cacio** [comment]
Alguma correção ? 
Estou tentando entender o Código que esta ali mas se já tiver uma solução para a classe agradeço.

**Comment by maisonsakamoto** [comment]
Oi @cacio, estou com o mesmo problema, eu consegui ajustar o layout p/ colocar até 20 nfe, mas acontece que isso ainda é pouco, tenho um caso aqui que o CTE vai levar mais de 50 NFes, então estou estudando uma solução p/ fazer paginação, se eu tiver sucesso eu mando aqui os códigos

**Comment by cacio** [comment]
Opa @maisonsakamoto , cara eu fiz aqui e caso queira posso compartilhar o codigo como eu tenho uns que fazem até 50 NFes então acaba danificando dacte e dai tive que entender  o codigo e depois disso tive um sucesso.

**Comment by cacio** [comment]
Não sei como posso mandar a classe ajustada ou se quiser que eu passe como eu fiz eu passo aqui e dai o master do projeto analisa e ajusta la.

**Comment by maisonsakamoto** [comment]
Oi @cacio resolvi também, vou atualizar meu fork, dai você da uma olhada, acho que ainda hoje antes do meio dia eu atualizo meu fork, o pull request aqui no projeto master talvez demora um pouco mais

**Comment by maisonsakamoto** [comment]
Coloquei já aqui só aguardar entrar a atualização [https://github.com/nfephp-org/sped-da/pull/32](https://github.com/nfephp-org/sped-da/pull/32)

**Comment by maisonsakamoto** [comment]
@cacio o Sr. @robmachado já incluiu no projeto, questão resolvida !

**Comment by Gleidson2012** [comment]
Creio que essa issue já pode ser fechada. =]
