### ISSUE TITLE
Nova Tag

### ISSUE THREAD

**Issue by joaoroyosilva** [nfephp-org/sped-da#306]
Boa tarde, é possível a geração de uma nova tag para atualização via composer de todas as alterações feitas desde a v2 até hoje? Tem algumas alterações como a inclusão da nota premiada e do CTeV3.

**Comment by robmachado** [comment]
Claro ... assim que tiver um tempo para alguns testes eu faço isso João, até a próxima semana deve ter a nova release (tag).

**Comment by robmachado** [comment]
Novo release v0.2.1
