### ISSUE TITLE
Trying to get property 'nodeValue' of non-object

### ISSUE THREAD

**Issue by eumanito** [nfephp-org/sped-da#314]
Estou tentando gerar uma Danfe a partir de um XML já protocolado e me retorna o erro: 
> Trying to get property 'nodeValue' of non-object

Verifiquei que isso ocorre porque meu XML não possui a tag "xMsg".

https://github.com/nfephp-org/sped-da/blob/e9b2cdf635f79097f5538941940f706591063036/src/NFe/Danfe.php#L3325-L3329

Alguém pode me ajudar?

**Comment by eumanito** [comment]
Enviei a PR e foi aprovada.

**Comment by joaohenriquefeitosa** [comment]
Conseguiu resolver? Qual era o problema?

**Comment by eumanito** [comment]
Sim, já está resolvido na branch atual. O problema era o que eu citei no post: precisava veriifcar se a tag xMsg existe antes de capturá-la.
