### ISSUE TITLE
Undefined variable: depecNumReg

### ISSUE THREAD

**Issue by eumanito** [nfephp-org/sped-da#349]
Erro identificado 8: 'Undefined variable: depecNumReg' C:\...\vendor\nfephp-org\sped-da\src\NFe\Danfe.php [linha:257]

Não estou utilizando a NFe de contingência, como faço para eliminar esse erro?

**Comment by robmachado** [comment]
Corrigido

**Comment by eumanito** [comment]
@robmachado, agora está com esse erro:

**Erro identificado 8: 'Undefined property: NFePHP\DA\NFe\Danfe::$marginf' C:\wamp64\www\nuvo\vendor\nfephp-org\sped-da\src\NFe\Danfe.php [linha:284]**

Estou fazendo assim:
https://github.com/nfephp-org/sped-da/blob/fb4e453de9e51b8d35bf8a3a137e5d8a2ff663e5/examples/nfe/danfe.php#L12-L28

**Comment by robmachado** [comment]
Ups !!! falha minha eu tinha visto e não corrigido

**Comment by eumanito** [comment]
@robmachado Funcionou, obrigado!

**Comment by robmachado** [comment]
Cara!! Obrigado a você por testar e me avisar !! Isso ajuda muito :+1:
