### ISSUE TITLE
Gerar mais de uma da no mesmo PDF

### ISSUE THREAD

**Issue by maisonsakamoto** [nfephp-org/sped-da#36]
Existe já implementado algo nesse sentido, eu enviar dois ou mais xml e a API montar as DAs no mesmo PDF ?

**Comment by robmachado** [comment]
@maisonsakamoto;

Isso é uma coisa no minimo "esquisita" de se fazer. Pode até ser uma necessidade sua e até de outros mas que é estranho isso é.
Respondendo a sua pergunta: NÃO

**Comment by eduardokum** [comment]
Tenho uma situação que preciso de juntar os pdfs, como estão armazenados eu so uno eles gerando um novo 

uso a lib

clegginabox/pdf-merger

```php
$pdf = new PDFMerger();
$pdf->addPDF('arquivo1.pdf');
$pdf->addPDF('arquivo2.pdf');
$pdf->addPDF('arquivo3.pdf');
$pdf->merge();
```

veja se te ajuda.

**Comment by maisonsakamoto** [comment]
Meu excelentíssimo usuário tinha essa opção no emissor gratuito, e esta exigindo agora no ERP que fizemos, pakaba mesmo...rssr

**Comment by maisonsakamoto** [comment]
@eduardokum vou ver se resolve já te aviso, obrigado desde já pela atenção

**Comment by robmachado** [comment]
Por que não estudou artes plasticas, bem feito !! heheheheh 
o pior que nem eu fui estudar engenharia e depois sistemas, inhaca !!!

**Comment by maisonsakamoto** [comment]
@robmachado engenharia, e largou porque se as engenharias ganha mai$, todo cara que é de TI é meu meio fora da normalidade mesmo..rsrsrs

**Comment by maisonsakamoto** [comment]
@eduardokum no projeto https://github.com/clegginabox/pdf-merger/tree/master/src/PDFMerger esta faltando dois arquivos:
use fpdi\FPDI;
use fpdf\FPDF;

Sabe onde consigo eles ? ( acho que o FPDF já tem aqui no sped-da )

**Comment by eduardokum** [comment]
Eu uso o do nfe-php, não tive que instalar nada, mais se por acaso não tiver tem que instalar, procura no packagist lá e instala

**Comment by robmachado** [comment]
@maisonsakamoto 

Vou fechar essa ISSUE pois não é algo que deva estar dento dessa API, pelo menos na minha opinião. 
Uma coisa que poderia até estar presente e que valeria a pena uma analise posterior seria agregar qualquer evento dentro do xml da sua própria NFe de origem e com isso implementar a impressão do DANFE + EVENTO (CCe por exemplo) em um mesmo PDF. Mas teríamos que estudar melhor isso e suas implicações pois isso não faz parte do desenho da SEFAZ, seira algo adicional e poderia ter outros impactos.
