### ISSUE TITLE
Powered by NFePHP é obrigatório?

### ISSUE THREAD

**Issue by eumanito** [nfephp-org/sped-da#367]
Boa tarde pessoal.

Ao utilizar esta biblioteca para gerar Danfe é obrigatório manter o texto "Powered by NFePHP®" no final da página? Se for opcional, então qual parâmetro devo utilizar para remover.

**Comment by robmachado** [comment]
É não tem ... se você estiver usando o seu fork e ele estiver **desatualizado** 

olha aqui https://github.com/nfephp-org/sped-da/blob/master/src/Common/DaCommon.php

Meu amigo Manito, eu digo essas "coisas" pelo seguinte:

- se vocês querem usar o seu fork, alterem e corrijam as coisas que não gostam, não precisam usar o repositório original o pacote é LGPL é livre para fazer o que quiser, desde que mencione a origem do código e mantenham os créditos no código, fora isso divrita-se;
- não particularmente você, mas são solicitadas e inseridas coisas reprováveis o tempo todo, especialmente nesse pacote;
- novamente não me refiro a você meu amigo, mas ao invés de ajudar de qq forma que seja a grande maioria somente pede, reclama e nem se dá ao trabalho de pelo menos LER o código que vão usar.

**Comment by robmachado** [comment]
PS: Agradeço a suas menções e aguardo em breve que você contribua  abrindo uma ISSUE, fazendo um PR, escrevendo alguma documentação, criando um vídeo para ajudar os estudantes e colegas menso habilidosos e treinados. Sucesso no seu ERP :+1:
