### ISSUE TITLE
Classe Danfce não funcional

### ISSUE THREAD

**Issue by evertongx** [nfephp-org/sped-da#37]
Estou implementando o NFCe e vi que essa classe está chamando classes do projeto antigo e uma classe QrCode que não corresponde com código implementado. Queria alguma luz sobre, por que posso até colaborar fazendo os ajustes necessários.

**Comment by robmachado** [comment]
Exato essa classe contêm muitos  e mitos BUGS, e em principio poderia depender apenas de sped-common, ou nem disso. Se depender de sped-common deve depender da versão 5.0 do sped-common e não da outra versão que está no branch master, pois isso será trocado em breve.

Para a Danfce é recomendado também usar a classe "Posprint" para gerar o código nativo da impressora térmica ESCPOS (Daruma, Bematech, Elgin, etc.), mas isso seria uma outra classe bem diferente dessa que gera o PDF. 

Essa classe deve receber o XML de uma nota modelo 65 por uma string ou por file e com isso criar a DANFCE. O QRCode deve ser apenas renderizado (como imagem) e não construído o seu conteúdo pois esse conteúdo  deve estar obrigatoriamente dentro do XML.

**Comment by evertongx** [comment]
Entendido, vou fazer os testes com a DanfePos para ver se ela já resolve meu problema então.
