### ISSUE TITLE
DANFE - Erro no status consultado para exibir "NFe cancelada"

### ISSUE THREAD

**Issue by neilvilela** [nfephp-org/sped-da#374]
Boa tarde, pessoal! Estava sem atualizar o código há um tempo e notei que o $situacaoExterna, que antes era recebido pela função printDANFE, não existe mais. E, em vez dele, agora existe a função `statusNFe`, que consulta o status do protocolo.

O problema que encontrei foi que, no caso da NF-e cancelada, os status consultados são os dos eventos, que não estão no mesmo XML do nfeProc, e a nota é sempre reconhecida como aceita.

Na nota denegada, já que a denegação faz parte do protocolo da NF-e, isso não é um problema.

Como seria a melhor forma de tratar isso? Estou tratando sobrescrevendo a função consultando um atributo meu para ver se a nota está cancelada, mas não creio que seja a melhor maneira.

**Comment by robmachado** [comment]
O sped-nfe tem uma classe que inclui o evento de cancelamento na NFe autorizada, isso permite marca-la como cancelada. 

vide https://github.com/nfephp-org/sped-nfe/blob/master/docs/Complements.md
