### ISSUE TITLE
DanfcePos monta pagamentos

### ISSUE THREAD

**Issue by evertongx** [nfephp-org/sped-da#38]
Estou com um problema no método monta nesse momento:
https://github.com/nfephp-org/sped-da/blob/master/src/NFe/DanfcePos.php#L243

Quando vai ler os pagamentos ele espera que $pag seja um array e no meu caso que só tem um pagamento $pag é um objeto. Seria alguma coisa errada na montagem do xml ou deveria arrumar para esperar um objeto nessa parte do método?

**Comment by robmachado** [comment]
Analise o código dessa classe, não foi eu quem a fez. E nem está testada
ainda pelo que eu saiba ...

Mas esse bloco tem algum erro pois não usa o indexador do for next

Roberto

**Comment by robmachado** [comment]
Esse script foi removido e está apenas em exemplos OLD apenas como referencia o posprint passou a ser apenas sugerido
