### ISSUE TITLE
Impressão de evento de carta de correção, erro na data.

### ISSUE THREAD

**Issue by raulti** [nfephp-org/sped-da#387]
Ao gerar um comprovante de carta de correção é exibido a seguinte exção: "date() expects parameter 2 to be int, string given".
no meu debug descobri que o erro acontece ao converter uma data na linha 375 da classe Daevento. Alguma resolução?

**Comment by evandromurilo** [comment]
Parece estar relacionado ao problema relatado em #385

**Comment by JakeDeGea** [comment]
yep, quase certeza que é o mesmo problema do #385

**Comment by EspetoRx** [comment]
Também estou com este mesmo erro na impressão de Daeventos de aprovação e de negação da aprovação.

**Comment by tiagofranco86** [comment]
Olá, estou utlizando a versao 0.2.6 e estou com o mesmo erro. Dei uma olhada nas resolucoes e vi que o erro esta relacionado a linha $tsHora = $this->toTimestamp($this->dhEvento); do arquivo NFePHP\DA\NFe\Daevento.php para utilizar a funcao  strtotime.

Porem ainda esta com o codigo antigo ($this->toTimestamp($this->dhEvento)) mesmo com o composer update. Poderia me auxliar?

**Comment by robmachado** [comment]
Quais são as datas que estão no XML em questão ???
Aparentemente não estão passando pelo regex do método!!

**Comment by robmachado** [comment]
A conversão usa um regex para validar e o timezone -05:00 não estava incluso. Foi corrigido em dev-master
