### ISSUE TITLE
Erro ao renderizar PDF sem logo em Daeevento

### ISSUE THREAD

**Issue by eumanito** [nfephp-org/sped-da#390]
Pessoal, não estou conseguindo gerar o PDF para Carta de Correção sem passar o logo.

```
$daevento = new Daevento($xml, $dadosEmitente);
header('Content-Type: application/pdf');
$pdf = $daevento->render($logo='');
```

O conteúdo é inválido e o PHP não consegue renderizar.
Aparece assim no navegador:
%PDF-1.3 3 0 obj <> endobj 4 0 obj <> stream x��Y�r�8��)�8�����=i,%�)��J����\`��p�R�L���0O�05�T�;��%Z �$)�M����� �)LL�◔��]�w�g���0�#I�J��h}�@���ȡ��V�q)R�H�)-�¿��Q��Y�B��3�D(Cޑ�����bq�DbSE�F�s�=��(Z��

Na classe Danfe() funciona! Tentei comparar as duas (Danfe vs Daevento) e não encontrei o que pode estar causando erro.

Alguém pode me ajudar?

**Comment by robmachado** [comment]
Colega !! para o navegador renderizar tem que passar o header de pdf (e pode ser que não funcione em qq navegador use o chrome) 
header("Content-type:application/pdf");
echo $pdf;

**Comment by eumanito** [comment]
@robmachado Estou passando o header de pdf, olha o que postei antes!

Devido a não ter o logo ele não consegue renderizar.

**Comment by robmachado** [comment]
Se não tem logo não passa ou passa NULL

**Comment by eumanito** [comment]
Exatamente, tentei passar uma string vazia ou null e não aceita.

Em sáb, 19 de set de 2020 15:34, Roberto L. Machado <
notifications@github.com> escreveu:

**Comment by robmachado** [comment]
Vou investigar isso

**Comment by sistemoc** [comment]
Sei que este issue já tem algum tempo, mas me deparei nesse erro neste momento e encontrei a solução...
Basta adicionar "exit;" (sem as aspas duplas) após o echo $pdf.

Exemplo:
$pdf = $daevento->render();
header('Content-type: application/pdf');
echo $pdf;
exit;

**Comment by bicosujo** [comment]
Show só colocar o exit; que funcionou
