### ISSUE TITLE
Atributo $this->logomarca ignorado quando $danfe->render() é chamado sem parametro logo

### ISSUE THREAD

**Issue by afbarboza94** [nfephp-org/sped-da#417]
Quando gero o DANFE pelo

$danfe = new Danfe($xml);
$danfe->render();

baseado no exemplo que esta na documentação sped-da/examples/nfe/danfe.php

mas sem passar o parâmetro $logo no método render, ele ignora completamente o que eu fiz em

$danfe->logoParameters($logo, 'C', false);

Escrevo mais como uma sugestão. O meu intuito era que o logo aparecesse em BW quando estivesse sem protocolo e colorido quando o xml estivesse protocolado. Para isso, eu acessei a classe DaCommom.php, encontrei o método _adjustImage_ e fiz a seguinte alteração:

DE
`protected function adjustImage($logo, $turn_bw = false)
    {
        if (empty($logo)) {
            return null;
        }
}`

PARA
`protected function adjustImage($logo, $turn_bw = false)
    {
        if (!empty($this->logomarca)) {
            return $this->logomarca;
        }

        if (empty($logo)) {
            return null;
        }
}`

**Comment by robmachado** [comment]
Esse tipo de comportamento cabe a você implementar em seu fork !!
