### ISSUE TITLE
Danfce saindo cortada quando existe a informação da nota premiada

### ISSUE THREAD

**Issue by crThiago** [nfephp-org/sped-da#457]
Em uma nota que consta as informações das dezenas da nota premiada de MS, as informações complementares estão saindo cortadas.
![image](https://user-images.githubusercontent.com/33141686/115297612-c75b0580-a132-11eb-8bb1-2946dac7218c.png)

**Comment by robmachado** [comment]
me mande esse xml para eu testar aqui ! 
linux.rlm@gmail.com

**Comment by robmachado** [comment]
corrigido em master
