### ISSUE TITLE
Pacote nfephp-org/posprint obrigatório para NFCe

### ISSUE THREAD

**Issue by JaedsonBarbosa** [nfephp-org/sped-da#458]
A geração do DANFE para NFC-e só funciona se o pacote nfephp-org/posprint estiver instalado e isso não é informado em lugar nenhum, perdi um dia todo tentando resolver isso sem entender o porquê de não estar funcionando, foi só instalar esse pacote e pá, funcionou.

**Comment by robmachado** [comment]
Estranho tenho várias instalações do sped-da e NUNCA coloquei que forma obrigatória o pacote posprint, provavelmente você está usando alguma versão antiga.
