### ISSUE TITLE
Consideração quanto aos totalizadores da Danfce

### ISSUE THREAD

**Issue by brunowinsite** [nfephp-org/sped-da#468]
Boa tarde.
Estamos utilizando a biblioteca para um projeto nosso. Porém, recentemente descobrimos algo estranho na hora de gerar Danfce’s.
Notamos que o campo “Valor Total R$”, o valor informado se refere ao valor da nota acrescido o valor de desconto da nota. Contudo, nos pareceu um pouco confusa a disposição dos demais elementos, tendo em vista que os acréscimos (como o frete, por exemplo) não é somado no valor total para gerar o “Valor a Pagar R$”, enquanto o desconto é diminuído desse valor total. Conforme imagem abaixo:

![print_danfce](https://user-images.githubusercontent.com/84988357/120028084-9b049580-bfca-11eb-8578-49f5b36037ae.png)

Consultando o “Manual de Especificações Técnicas do DANFE NFC-e” versão 5.1, deparamos com um modelo de totalizações que nos pareceu menos confuso. Segue a imagem em anexo:

![print_receita](https://user-images.githubusercontent.com/84988357/120028151-b2dc1980-bfca-11eb-82a8-79a7423f6788.png)

Gostaríamos de saber se o modelo atual realmente está com problemas ou se essa seria mais uma questão de preferência de disposição dos itens. Caso isso de fato seja algo a ser corrigido, podemos realizar um pull request. Agradecemos desde já pela disponibilidade e atenção.

**Comment by robmachado** [comment]
Não é preferencia não!
É esquecimento mesmo !!
Como o valor bruto é "calculado" não foi calculado com o valor do frete
Deve estar corrigido em master

**Comment by brunowinsite** [comment]
Acabei de verificar os commits, nesse cálculo não deveria considerar os demais campos para formação do valor total da nota, como seguro por exemplo? Conforme o MOC 7.0 (p.122), o valor da nota seria composto pelos seguindo valores:

![print_campos_vnf](https://user-images.githubusercontent.com/84988357/120035905-b7f29600-bfd5-11eb-8e08-8808cd991f2c.png)

Talvez não seria interessante deixar o valor bruto como sendo vProd?

**Comment by robmachado** [comment]
Não meu amigo !!
Os dados totais vem diretamente do XML, apenas existe a diferença que o "VALOR BRUTO" que está no DANFCE não existe no XML ele é construído (calculado), pessoalmente acho inútil, mas cada um com a sua "esquizofrenia" hehehehe  
Esses outros valores que você menciona não existem numa NFCe ou não são destacados !

**Comment by brunowinsite** [comment]
Ok, muito obrigado.
