### ISSUE TITLE
Quebra de linha carta de correção

### ISSUE THREAD

**Issue by guicalabria** [nfephp-org/sped-da#474]
Vi que as cartas de correção estavam saindo sem quebra de linha.
Ao gravar a carta troco \n por ; 
É para deixar com \n mesmo?
na linha 492 a 496 do arquivo Daevento.php troquei por:
        if ($this->tpEvento == '110110') {
            $texto = str_replace(";","\n",$this->xCorrecao);
        } elseif ($this->tpEvento == '110111') {
            $texto = str_replace(";","\n",$this->xJust);
        }

**Comment by robmachado** [comment]
Então Guilherme, no caso da quebra de linha nos XML é melhor trocar o "\n" por ";" dá menos problemas.

E quanto a correção no sped-da eu faço essa alteração. Nunca me preocupei com isso pois uma CCe em PDF para mim não faz mito sentido.

**Comment by robmachado** [comment]
Tá em master!

**Comment by guicalabria** [comment]
Ok, obrigado!
