### ISSUE TITLE
Erro ao gerar Danfe simples de NF-e sem frete

### ISSUE THREAD

**Issue by victorvilella** [nfephp-org/sped-da#477]
Olá a todos.

Gostaria de levantar um assunto que pode ser que alguém em algum momento vá ter que debater.

# No caso de um XML que o modFrete seja igual a 9 (Sem frete), faz algum sentido imprimir-se o DANFe simples?

## Caso sim:
Deve-se proteger, no arquivo [`src/NFe/DanfeSimples.php`](src/NFe/DanfeSimples.php) para montar as informações da transportadora apenas se existir a posição `transporta` no método `monta()`.

## Caso não:
Deve-se lançar uma exceção caso o XML não possua as informações de frete ao invocar o método `monta()`.

O que vocês acham? Do jeito que foi implementado, acredito que esteja errado de qualquer forma.

**Comment by robmachado** [comment]
Não tem "CERTO" ou "ERRADO" quando se trata de DANFE.

Em princípio, apenas deve ser impresso o DANFE *caso haja transporte de
mercadorias*, mas imprimem qualquer coisa, até nota complementar.

Roberto

**Comment by victorvilella** [comment]
Bom, sendo assim, na regra de negócio do ERP que dou manutenção, é melhor dar a opção do DANFe simples, independente da discussão. De qualquer forma, segue o PR #478 .

**Comment by victorvilella** [comment]
PR 478 aprovado, o projeto a partir de agora passa a montar o Danfe simples. Obrigado, @robmachado.
