### ISSUE TITLE
Erro "Implicit conversion" aparece com o PHP 8.1 devido à biblioteca tc-lib-barcode 1.15

### ISSUE THREAD

**Issue by maxiwell** [nfephp-org/sped-da#501]
Olá, estou usando a lib `sped-da` com PHP 8.1 e o erro abaixo acontece quando tento [contruir o objeto barcode](https://github.com/nfephp-org/sped-da/blob/master/src/CTe/Dacte.php#L3797).
```
Uncaught Exception: Erro identificado 8192: 'Implicit conversion from float 0.25 to int loses precision' 
/home/maxiwell/devel/vendor/tecnickcom/tc-lib-barcode/src/Type/Square/QrCode/Encoder.php [linha:215] in 
/home/maxiwell/devel/vendor/nfephp-org/sped-da/src/Common/DaCommon.php:125
```

Isso foi corrigido na lib `tc-lib-barcode` no dia 9/12/2021 e está presente na versão 1.17.11: https://github.com/tecnickcom/tc-lib-barcode/commit/60dcfc4ccbc6de214ffdff82ce4d1adf2d95bc1c

Existe algum plano para atualizar a versão da `tc-lib-barcode` para deixar a `sped-da` compatível com o PHP 8?

**Comment by robmachado** [comment]
Tenho que checar para ver se não vai quebrar quando usamos o php 7.4

**Comment by robmachado** [comment]
Já atualizei na branch master

**Comment by robmachado** [comment]
@maxiwell Você usa apenas o sped-da ou usa os outros pacotes como sped-nfe em PHP8.1. Se sim ficaria grato se me informa-se de qualquer problema de compatibilidade, pois esse semestre pretendo mover todos os pacotes SPED para php8.*

**Comment by maxiwell** [comment]
@robmachado Muito obrigado, funcionou like a charm. Estamos migrando para o PHP 8.1 e o projeto usa a lib `sped-nfe` e a `sped-da`. Se aparecer novos erros lhe aviso. Obrigado novamente.
