### ISSUE TITLE
Versão 3.0 - CTe

### ISSUE THREAD

**Issue by maisonsakamoto** [nfephp-org/sped-da#51]
Boa Tarde, alguém sabe se o sped-da já atende a versão 3.0 do CTe ?

**Comment by robmachado** [comment]
Mailson;
O melhor caminho é testar acredito que esteja funcional mas como não uso não tenho certeza.

**Comment by maisonsakamoto** [comment]
sim estou testando, o que tem é versão 2.0, como a 3 é praticamente a 2 com algumas informações a **menos** estou só comentando alguns trechos de códigos..rsrssr

**Comment by samuelbasso** [comment]
Segundo o Gustavo que trabalha comigo e também está ajudando no desenvolvimento não saiu ainda um manual da DACTE para a 3.0, sendo assim, utilizando o que tem hoje está funcional, tirando um campo que não me recordo que não tem mais a tag no XML 3.0.

**Comment by maisonsakamoto** [comment]
saiu a forma de pagamento, quase tudo do modal rodoviário. Então só omitindo esses campos já esta certo? 
teria que aparecer na impressão alguma das tags novas que foi adicionada na versão 3.0 ?

**Comment by maisonsakamoto** [comment]
Amigos achei uma nota técnica da DACTE versão 3.0 segue o link
http://www.cte.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=UUmvMKqB/fk=

muda um pouco sim, e tem que apresentar alguns campos novos também.... vou fazer assim que terminar eu faço um PR

**Comment by maisonsakamoto** [comment]
todas as alterações esta contemplada no 
https://github.com/nfephp-org/sped-da/pull/53
