### ISSUE TITLE
Danfe Simplificado não mostra peso bruto em alguns casos

### ISSUE THREAD

**Issue by matheusryndack** [nfephp-org/sped-da#512]
Notei que não estava saindo o peso bruto/líquido na danfesimplificada, e averiguando encontrei esse trecho de código que pula o volume caso não tenha a tag 'esp'. (Linha 274 do arquivo DanfeSimples.php).

Esse comportamento é esperado ou é um bug?
Fiquei na dúvida, porque tem um comentário especificando falando "Espécie não especificada na transportadora (por erro de preenchimento do XML)", no entanto tenho XMLs autorizados sem essa tag, e ela não é obrigatória.

Posso efetuar a correção e um Pull Request? Minha sugestão é validar a existência dos campos de peso em si, e não da tag 'esp'.

**Comment by robmachado** [comment]
Pode; mas seja cuidadoso para não fazer outras alterações

**Comment by matheusryndack** [comment]
Feito!
