### ISSUE TITLE
Logo PNG com fundo preto

### ISSUE THREAD

**Issue by douglasduarte** [nfephp-org/sped-da#549]
Olá, tenho instalado no PHP a biblioteca de imagem GD e na visualização das Danfes as logos PNG transparentes aparecem com o fundo preto, teria alguma forma de corrigir este problema?

![image](https://user-images.githubusercontent.com/42970432/189672520-a0997ff4-bcae-48b6-b82c-76bd2a42c90d.png)

**Comment by robmachado** [comment]
Você deve tratar as imagens antes de usa-las, não é tarefa da biblioteca tratar as imagens !
A biblioteca tem como objetivo pegar os dados do XML é gerar um PDF que atenda aos requisitos da Receita e das SEFAZ, nada mais nada menos.
