### ISSUE TITLE
PHP 8.2: Diversos avisos "deprecated" no projeto

### ISSUE THREAD

**Issue by estherpeixoto** [nfephp-org/sped-da#575]
Olá, venho tentado utilizar a sped-da com **PHP 8.2.4** porém ao rodar o `composer test` é exibido diversos avisos de depreciação, como este:

```
Deprecated: Creation of dynamic property NFePHP\DA\MDFe\Damdfe::$infMDFe is deprecated in C:\Projetos\sped-da\src\MDFe\Damdfe.php on line 73
```

Output completo:
[output.txt](https://github.com/nfephp-org/sped-da/files/11235441/output.txt)

Eu poderia fazer um PR para corrigir estes avisos, se tiverem interesse.

**Comment by robmachado** [comment]
Deprecated não é erro então desative o disparo de avisos ou ignore por enquanto
