### ISSUE TITLE
Alteração no componente para corrigir validação ao gerar MDF-e

### ISSUE THREAD

**Issue by Emerson-Gabriel** [nfephp-org/sped-da#576]
Conforme layout do MDF-e a tag RNTRC (do emitente) não é obrigatória: 
![image](https://user-images.githubusercontent.com/18463395/233381720-07df4ecc-2cc7-41ef-9856-b3ff7390acae.png)
 
 Porém no componente, ao gerar o MDF-e, temos o seguinte trecho: 
![image](https://user-images.githubusercontent.com/18463395/233389461-d4d3f9c9-6821-477f-886e-e3e0b313958f.png)
 
 Ou seja, vemos que é verificado se a tag infANTT está preenchida e em seguida é capturado o RNTRC.
 
 Porém se for informado um CIOT ou Contratante no MDF-e a tag infANTT estará preenchida, mas o RNTRC poderá não estar informado no XML.
 
 Com isso o componente gera uma exceção com a seguinte mensagem: `"Trying to get property 'nodeValue' of non-object"`
 
 Pois ele está tentando capturar o RNTRC mesmo quando não está informado.
 
 Com isso deve ser feito uma melhoria para validar realmente se o campo RNTRC estiver preenchido, captura-lo caso contrário não capturar, exemplo que fiz: 
![image](https://user-images.githubusercontent.com/18463395/233393448-f95ead15-d884-48d4-a528-29ae8357f82c.png)
 
 Aguardo retorno.

**Comment by guilherme-santos** [comment]
Esse PR causou um bug, para casos onde não temos `infANTT` teremos o seguinte erro
Call to a member function getElementsByTagName() on null at /usr/share/nginx/web/vendor/nfephp-org/sped-da/src/MDFe/Damdfe.php:172
