### ISSUE TITLE
Instrução Técnica 2024.002  Altera Tabela de Meios de Pagamento

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-da#599]
Entra em vigor em produção em 01/07/2024 no ambiente de produção, a alteração da Tabela de Meios de Pagamento.
vide [IT 2024.002](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=1rS27BEDS6c=)

A nova tabela (que agora contêm mais tipos de pagamentos e observações para esclarecer melhor o que cada código significa).
vide [Nova Tabela de Meios de Pagamento]([https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=v5k1Ww0z Sw=](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=v5k1Ww0z%20Sw=))

**Comment by SuportecTL** [comment]
Bom dia, sabe se tem alguma previsão para que funcione em homologação (atualização schemas) por parte da Sefaz?

**Comment by davidvrsantos** [comment]
@SuportecTL já foi resolvido, pode atualizar.
