### ISSUE TITLE
Add member

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-da#8]
Bom dia Roberto, pode me adicionar como contributor/member? Obrigado! :-)

**Comment by robmachado** [comment]
Todos os interessados foram Adicionados, mas lembre-se de "forkar" o repositório para seu usuário e usar os "pull requests" para alterar, podemos fazer com que cada pull request de um de nós seja verificado por um dos outros antes de permitir a atualização. Isso valerá mais quando já estiver em versão estável.
