### ISSUE TITLE
Problema com dependências "nfephp-org/sped-common": "5.0.13",

### ISSUE THREAD

**Issue by dbemfica** [nfephp-org/sped-da#87]
No composer do projeto tem o requerimento "nfephp-org/sped-common": "5.0.13" mas no projeto do sped-common já estamos na versão 5.0.19.

Para quem está usando o sped-nfe já foi instalada a mais nova versão do sped-common e ao tentar instalar o sped-da está dando conflito na verão do sped-common.

Não seria o caso de trocar no composer para "nfephp-org/sped-common" : "^5.0", ao invés de "nfephp-org/sped-common": "5.0.13"?

**Comment by robmachado** [comment]
Corrigido !
