### ISSUE TITLE
FPDF The each() function is deprecated php 7.2

### ISSUE THREAD

**Issue by mrcarromesa** [nfephp-org/sped-da#94]
Não sei se é conhecimento do(s) desenvolvedor(es), está ocorrendo o seguinte erro: 

referente a linha que possuí o seguinte trecho de código: while (list($file,$info) = each($this->images)) { ...

no script: nfephp-org/sped-da/src/Legacy/FPDF/Fpdf.php
está gerando esse erro:
The each() function is deprecated. 
Na versão 7.2 do php

Se já for de conhecimento favor ignorar

**Comment by robmachado** [comment]
Isso é importante, corrigir !!!
Muito grato pelo aviso. Estamos aguardando o TCPDF ser terminado em sua nova versão para usá-lo como base, mas isso está demorando um bocado !

**Comment by Litiano** [comment]
Olá @robmachado . Vi que já corrigiram esse bug, mas quando rodo composer upgrade não atualiza para v0.1.9, no https://packagist.org/packages/nfephp-org/sped-da ainda está a versão v0.1.7.

**Comment by robmachado** [comment]
Removido
